version: "3.9"
services:
  finch:
    image: finch:latest
    build:
      context: ./finch
    ports:
      - target: 3000
        published: 3000
        mode: host
    env_file: ./.env
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      rollback_config:
        parallelism: 0
      update_config:
        parallelism: 0
        failure_action: rollback
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 4G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000/health-check"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
